In [57]:
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
from sklearn.preprocessing import OneHotEncoder
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

In [61]:
df=pd.read_csv('supershops.csv')

In [62]:
df.head()
df1=df.copy()
df2=df.copy()
df3=df.copy()
df4=df.copy()

In [63]:
df.shape

(50, 5)

In [64]:
df.head()

   Marketing Spend  Administration  Transport     Area     Profit
0        114523.61       136897.80  471784.10    Dhaka  192261.83
1        162597.70       151377.59  443898.53      Ctg  191792.06
2        153441.51       101145.55  407934.54  Rangpur  191050.39
3        144372.41       118671.85  383199.62    Dhaka  182901.99
4        142107.34        91391.77  366168.42  Rangpur  166187.94

Perform linear regression without any encoding and Normalizationb

In [66]:
x=df.drop(['Area','Profit'],axis=1)
y=df[['Profit']]

In [67]:
x.head()

   Marketing Spend  Administration  Transport
0        114523.61       136897.80  471784.10
1        162597.70       151377.59  443898.53
2        153441.51       101145.55  407934.54
3        144372.41       118671.85  383199.62
4        142107.34        91391.77  366168.42

In [69]:
y.shape

(50, 1)

In [102]:
xtrain1,xtest1,ytrain1,ytest1=train_test_split(x,y,random_state=20,test_size=0.30)

In [103]:
from sklearn.linear_model import LinearRegression

In [104]:
model=LinearRegression()

In [105]:
model.fit(xtrain1,ytrain1)

LinearRegression()

In [106]:
ypred = model.predict(xtest1)
print("R² score:", r2_score(ytest1, ypred))
print("MSE:", mean_squared_error(ytest1, ypred))
print("MAE:", mean_absolute_error(ytest1, ypred))

R² score: 0.8877479434849371
MSE: 190963774.119891
MAE: 9894.800310690112

Normalization

In [6]:
from sklearn.preprocessing import MinMaxScaler
m=MinMaxScaler()

In [7]:
df_mar=m.fit(df[['Marketing Spend']])
df_mar

MinMaxScaler()

In [10]:
df[["Marketing Spend"]]=m.transform(df[['Marketing Spend']])
df.head()

   Marketing Spend  Administration  Transport     Area     Profit
0         0.691606       136897.80  471784.10    Dhaka  192261.83
1         0.983305       151377.59  443898.53      Ctg  191792.06
2         0.927748       101145.55  407934.54  Rangpur  191050.39
3         0.872719       118671.85  383199.62    Dhaka  182901.99
4         0.858975        91391.77  366168.42  Rangpur  166187.94

In [11]:
#Scaling all numeric row except target 

scaler = MinMaxScaler()

numeric_cols = df.select_dtypes(include=np.number).columns

for col in numeric_cols:
    if col != "Profit":   # target বাদ
        df[[col]] = scaler.fit_transform(df[[col]])

df.head()

   Marketing Spend  Administration  Transport     Area     Profit
0         0.691606        0.651744   1.000000    Dhaka  192261.83
1         0.983305        0.761972   0.940654      Ctg  191792.06
2         0.927748        0.379579   0.864115  Rangpur  191050.39
3         0.872719        0.512998   0.811474    Dhaka  182901.99
4         0.858975        0.305328   0.775228  Rangpur  166187.94

In [117]:
X=df.drop('Profit',axis=1)
Y=df[['Profit']]

In [118]:
Y.shape

(50, 1)

In [119]:
X.shape

(50, 3)

In [120]:
encoder = OneHotEncoder(drop='first', sparse_output=False)
cat_cols = X.select_dtypes(include='object').columns
for col in cat_cols:
    
    encoded = encoder.fit_transform(X[[col]])
    
    encoded_df = pd.DataFrame(
        encoded,
        columns=encoder.get_feature_names_out([col])
    )
    
    X = pd.concat([X, encoded_df], axis=1)
    df.drop(col, axis=1, inplace=True)

X.head()

   Marketing Spend  Administration  Transport
0         0.898279        0.560753   2.232914
1         1.957622        1.082807   1.979757
2         1.755860       -0.728257   1.653261
3         1.556017       -0.096365   1.428707
4         1.506104       -1.079919   1.274090

In [121]:
xtrain,xtest,ytrain,ytest=train_test_split(X,Y,random_state=30,test_size=0.30)

In [122]:
print("X shape:", X.shape)
print("Y shape:", Y.shape)

X shape: (50, 3)
Y shape: (50, 1)

In [123]:
from sklearn.linear_model import LinearRegression

In [124]:
lr=LinearRegression()
lr.fit(xtrain,ytrain)

LinearRegression()

In [125]:
ypred = lr.predict(xtest)
print("R² score:", r2_score(ytest, ypred))
print("MSE:", mean_squared_error(ytest, ypred))
print("MAE:", mean_absolute_error(ytest, ypred))

R² score: 0.8939177575806647
MSE: 50636810.4833695
MAE: 5613.291840940808

Standard Scaler

In [126]:

from sklearn.preprocessing import StandardScaler

standard = StandardScaler()

numeric_cols = df1.select_dtypes(include=np.number).columns

for col in numeric_cols:
    if col != "Profit":  
        df1[[col]] = standard.fit_transform(df1[[col]])

df1.head()

   Marketing Spend  Administration  Transport     Area     Profit
0         0.898279        0.560753   2.232914    Dhaka  192261.83
1         1.957622        1.082807   1.979757      Ctg  191792.06
2         1.755860       -0.728257   1.653261  Rangpur  191050.39
3         1.556017       -0.096365   1.428707    Dhaka  182901.99
4         1.506104       -1.079919   1.274090  Rangpur  166187.94

In [127]:
X1=df1.drop(['Area','Profit'],axis=1)
Y1=df1[['Profit']]

In [128]:
xtrain2,xtest2,ytrain2,ytest2=train_test_split(X1,Y1,random_state=30,test_size=0.30)

In [129]:
from sklearn.linear_model import LinearRegression

In [130]:
lr1=LinearRegression()

In [131]:
lr1.fit(xtrain2,ytrain2)

LinearRegression()

In [132]:
ypred = lr1.predict(xtest2)
print("R² score:", r2_score(ytest2, ypred))
print("MSE:", mean_squared_error(ytest2, ypred))
print("MAE:", mean_absolute_error(ytest2, ypred))

R² score: 0.8939177575806648
MSE: 50636810.48336944
MAE: 5613.291840940804

Max abs Scaler

In [133]:
from sklearn.preprocessing import MaxAbsScaler


maxabs = MaxAbsScaler()

numeric_cols = df2.select_dtypes(include=np.number).columns

for col in numeric_cols:
    if col != "Profit":   # target বাদ
        df2[[col]] = maxabs.fit_transform(df2[[col]])

df2.head()

   Marketing Spend  Administration  Transport     Area     Profit
0         0.692617        0.749527   1.000000    Dhaka  192261.83
1         0.983359        0.828805   0.940893      Ctg  191792.06
2         0.927985        0.553781   0.864664  Rangpur  191050.39
3         0.873136        0.649738   0.812235    Dhaka  182901.99
4         0.859438        0.500378   0.776136  Rangpur  166187.94

In [134]:
X2=df2.drop(['Area','Profit'],axis=1)
Y2=df2[['Profit']]

In [138]:
X2.shape

(50, 3)

In [139]:
Y2.shape

(50, 1)

In [140]:
xtrain3,xtest3,ytrain3,ytest3=train_test_split(X2,Y2,random_state=30,test_size=0.30)

In [142]:
lr3=LinearRegression()
lr3.fit(xtrain3,ytrain3)

LinearRegression()

In [143]:
ypred = lr3.predict(xtest3)
print("R² score:", r2_score(ytest3, ypred))
print("MSE:", mean_squared_error(ytest3, ypred))
print("MAE:", mean_absolute_error(ytest3, ypred))

R² score: 0.893917757580665
MSE: 50636810.48336931
MAE: 5613.2918409407985

Robust Scaler

In [144]:
from sklearn.preprocessing import RobustScaler

robust = RobustScaler()

numeric_cols = df3.select_dtypes(include=np.number).columns

for col in numeric_cols:
    if col != "Profit":   
        df3[[col]] = robust.fit_transform(df3[[col]])

df3.head()

   Marketing Spend  Administration  Transport     Area     Profit
0         0.672530        0.345355   1.479462    Dhaka  192261.83
1         1.452113        0.697565   1.301890      Ctg  191792.06
2         1.303634       -0.524290   1.072875  Rangpur  191050.39
3         1.156567       -0.097977   0.915365    Dhaka  182901.99
4         1.119836       -0.761543   0.806912  Rangpur  166187.94

In [145]:
X3=df3.drop(['Area','Profit'],axis=1)
Y3=df3[['Profit']]

In [149]:
xtrain4,xtest4,ytrain4,ytest4=train_test_split(X3,Y3,random_state=45,test_size=0.30)

In [150]:
lr4=LinearRegression()

In [151]:
lr4.fit(xtrain4,ytrain4)

LinearRegression()

In [154]:
ypred = lr4.predict(xtest4)
print("R² score:", r2_score(ytest4, ypred))
print("MSE:", mean_squared_error(ytest4, ypred))
print("MAE:", mean_absolute_error(ytest4, ypred))

R² score: 0.896328855487526
MSE: 177884672.2045736
MAE: 7712.009503624094