In [1]:
import pandas as pd

In [4]:
df=pd.read_csv("supershops.csv")

In [5]:
df.head()

   Marketing Spend  Administration  Transport     Area     Profit
0        114523.61       136897.80  471784.10    Dhaka  192261.83
1        162597.70       151377.59  443898.53      Ctg  191792.06
2        153441.51       101145.55  407934.54  Rangpur  191050.39
3        144372.41       118671.85  383199.62    Dhaka  182901.99
4        142107.34        91391.77  366168.42  Rangpur  166187.94

In [6]:
#Drop target profit from the dataset
xx = df.drop(["Profit"],axis="columns")
x2=xx.copy()
x3=xx.copy()
x4=xx.copy()
xx.head()

   Marketing Spend  Administration  Transport     Area
0        114523.61       136897.80  471784.10    Dhaka
1        162597.70       151377.59  443898.53      Ctg
2        153441.51       101145.55  407934.54  Rangpur
3        144372.41       118671.85  383199.62    Dhaka
4        142107.34        91391.77  366168.42  Rangpur

In [7]:
#Marketing Spend  Normalization
from sklearn.preprocessing import MinMaxScaler
m=MinMaxScaler()

In [8]:
df_mar=m.fit(df[["Marketing Spend"]])
df_mar

MinMaxScaler()

In [9]:
df.head()

   Marketing Spend  Administration  Transport     Area     Profit
0        114523.61       136897.80  471784.10    Dhaka  192261.83
1        162597.70       151377.59  443898.53      Ctg  191792.06
2        153441.51       101145.55  407934.54  Rangpur  191050.39
3        144372.41       118671.85  383199.62    Dhaka  182901.99
4        142107.34        91391.77  366168.42  Rangpur  166187.94

In [10]:
df[["Marketing Spend"]]=m.transform(df[["Marketing Spend"]])
df

    Marketing Spend  Administration  Transport     Area     Profit
0          0.691606       136897.80  471784.10    Dhaka  192261.83
1          0.983305       151377.59  443898.53      Ctg  191792.06
2          0.927748       101145.55  407934.54  Rangpur  191050.39
3          0.872719       118671.85  383199.62    Dhaka  182901.99
4          0.858975        91391.77  366168.42  Rangpur  166187.94
5          0.796900        99814.71  362861.36    Dhaka  156991.12
6          0.813517       147198.87  127716.82      Ctg  156122.51
7          0.787321       145530.06  323876.68  Rangpur  155752.60
8          0.728127       148718.95  311613.29    Dhaka  152211.77
9          0.745070       108679.17  304981.62      Ctg  149759.96
10         0.615089       110594.11  229160.95  Rangpur  146121.95
11         0.607558        91790.61  249744.55      Ctg  144259.40
12         0.566248       127320.38  249839.44  Rangpur  141585.52
13         0.554893       135495.07  252664.93      Ctg  134307.35
14         0.724490       156547.42  256512.92  Rangpur  132602.65
15         1.000000       122616.84  261776.23    Dhaka  129917.04
16         0.470071       121597.55  264346.06      Ctg  126992.93
17         0.571062       145077.58  282574.31    Dhaka  125370.37
18         0.553417       114175.79  294919.57  Rangpur  124266.90
19         0.521080       153514.11  294919.57    Dhaka  122776.86
20         0.459396       113867.30  298664.47      Ctg  118474.03
21         0.472355       153773.43  299737.29    Dhaka  111313.02
22         0.445688       122782.75  303319.26  Rangpur  110352.25
23         0.406478       105751.03  304768.73  Rangpur  108733.99
24         0.464191        99281.34  140574.81    Dhaka  108552.04
25         0.389077       139553.16  137962.62      Ctg  107404.34
26         0.453784       144135.98  134050.07  Rangpur  105733.54
27         0.434238       127864.55  353183.81    Dhaka  105008.31
28         0.397492       182645.56  118148.20  Rangpur  103282.38
29         0.394785       153032.06  107138.38    Dhaka  101004.64
30         0.372875       115641.28   91131.24  Rangpur   99937.59
31         0.367668       152701.92   88218.23    Dhaka   97483.56
32         0.381457       129219.61   46085.25      Ctg   97427.84
33         0.333432       103057.49  214634.81  Rangpur   96778.92
34         0.278410       157693.92  210797.67      Ctg   96712.80
35         0.275910        85047.44  205517.64    Dhaka   96479.51
36         0.170634       127056.21  201126.82  Rangpur   90708.19
37         0.264114        51283.14  197029.42      Ctg   89949.14
38         0.119458        65947.93  185265.10    Dhaka   81229.06
39         0.230672        82982.09  174999.30      Ctg   81005.76
40         0.171184       118546.05  172795.67      Ctg   78239.91
41         0.165957        84710.77  164470.71  Rangpur   77798.83
42         0.140157        96189.63  148001.11      Ctg   71498.49
43         0.090795       127382.30   35534.17    Dhaka   69758.98
44         0.131279       154806.14   28334.72      Ctg   65200.33
45         0.002780       124153.04    1903.93    Dhaka   64926.08
46         0.004693       115816.21  297114.46  Rangpur   49490.75
47         0.004693       135426.92  297114.46      Ctg   42559.73
48         0.000000        51743.15  148001.11    Dhaka   35673.41
49         0.000000       116983.80   45173.06      Ctg   14681.40

In [11]:
#Fit and Transfrom in a single line
df[["Administration"]]=m.fit_transform(df[["Administration"]])
df

    Marketing Spend  Administration  Transport     Area     Profit
0          0.691606        0.651744  471784.10    Dhaka  192261.83
1          0.983305        0.761972  443898.53      Ctg  191792.06
2          0.927748        0.379579  407934.54  Rangpur  191050.39
3          0.872719        0.512998  383199.62    Dhaka  182901.99
4          0.858975        0.305328  366168.42  Rangpur  166187.94
5          0.796900        0.369448  362861.36    Dhaka  156991.12
6          0.813517        0.730161  127716.82      Ctg  156122.51
7          0.787321        0.717457  323876.68  Rangpur  155752.60
8          0.728127        0.741733  311613.29    Dhaka  152211.77
9          0.745070        0.436929  304981.62      Ctg  149759.96
10         0.615089        0.451506  229160.95  Rangpur  146121.95
11         0.607558        0.308364  249744.55      Ctg  144259.40
12         0.566248        0.578836  249839.44  Rangpur  141585.52
13         0.554893        0.641066  252664.93      Ctg  134307.35
14         0.724490        0.801327  256512.92  Rangpur  132602.65
15         1.000000        0.543030  261776.23    Dhaka  129917.04
16         0.470071        0.535270  264346.06      Ctg  126992.93
17         0.571062        0.714013  282574.31    Dhaka  125370.37
18         0.553417        0.478772  294919.57  Rangpur  124266.90
19         0.521080        0.778236  294919.57    Dhaka  122776.86
20         0.459396        0.476424  298664.47      Ctg  118474.03
21         0.472355        0.780210  299737.29    Dhaka  111313.02
22         0.445688        0.544293  303319.26  Rangpur  110352.25
23         0.406478        0.414638  304768.73  Rangpur  108733.99
24         0.464191        0.365388  140574.81    Dhaka  108552.04
25         0.389077        0.671958  137962.62      Ctg  107404.34
26         0.453784        0.706845  134050.07  Rangpur  105733.54
27         0.434238        0.582978  353183.81    Dhaka  105008.31
28         0.397492        1.000000  118148.20  Rangpur  103282.38
29         0.394785        0.774566  107138.38    Dhaka  101004.64
30         0.372875        0.489928   91131.24  Rangpur   99937.59
31         0.367668        0.772053   88218.23    Dhaka   97483.56
32         0.381457        0.593294   46085.25      Ctg   97427.84
33         0.333432        0.394134  214634.81  Rangpur   96778.92
34         0.278410        0.810055  210797.67      Ctg   96712.80
35         0.275910        0.257032  205517.64    Dhaka   96479.51
36         0.170634        0.576825  201126.82  Rangpur   90708.19
37         0.264114        0.000000  197029.42      Ctg   89949.14
38         0.119458        0.111636  185265.10    Dhaka   81229.06
39         0.230672        0.241309  174999.30      Ctg   81005.76
40         0.171184        0.512041  172795.67      Ctg   78239.91
41         0.165957        0.254469  164470.71  Rangpur   77798.83
42         0.140157        0.341852  148001.11      Ctg   71498.49
43         0.090795        0.579307   35534.17    Dhaka   69758.98
44         0.131279        0.788072   28334.72      Ctg   65200.33
45         0.002780        0.554724    1903.93    Dhaka   64926.08
46         0.004693        0.491260  297114.46  Rangpur   49490.75
47         0.004693        0.640547  297114.46      Ctg   42559.73
48         0.000000        0.003502  148001.11    Dhaka   35673.41
49         0.000000        0.500148   45173.06      Ctg   14681.40

In [21]:
# Loop for perform  normalization transoformation
from sklearn.preprocessing import MinMaxScaler
scaler=MinMaxScaler()
for col in xx.columns:
    if pd.api.types.is_numeric_dtype(xx[col]):
        xx[col]=scaler.fit_transform(xx[[col]])
    else:
        continue

xx.head()

   Marketing Spend  Administration  Transport     Area
0         0.691606        0.651744   1.000000    Dhaka
1         0.983305        0.761972   0.940654      Ctg
2         0.927748        0.379579   0.864115  Rangpur
3         0.872719        0.512998   0.811474    Dhaka
4         0.858975        0.305328   0.775228  Rangpur

In [26]:
#Standarization on whole dataset
#x2.head()
from sklearn.preprocessing import StandardScaler
standard=StandardScaler()
for col in x2.columns:
    if pd.api.types.is_numeric_dtype(x2[col]):
        x2[col]=standard.fit_transform(x2[[col]])
    else:
        continue

x2.head()

   Marketing Spend  Administration  Transport     Area
0         0.898279        0.560753   2.232914    Dhaka
1         1.957622        1.082807   1.979757      Ctg
2         1.755860       -0.728257   1.653261  Rangpur
3         1.556017       -0.096365   1.428707    Dhaka
4         1.506104       -1.079919   1.274090  Rangpur

In [29]:
#Robust Scaler on whole dataset


from sklearn.preprocessing import RobustScaler
robust=RobustScaler()

for col in x3.columns:
    if pd.api.types.is_numeric_dtype(x3[col]):
        x3[col]=robust.fit_transform(x3[[col]])
    else:
        continue
x3.head()

   Marketing Spend  Administration  Transport     Area
0         0.672530        0.345355   1.479462    Dhaka
1         1.452113        0.697565   1.301890      Ctg
2         1.303634       -0.524290   1.072875  Rangpur
3         1.156567       -0.097977   0.915365    Dhaka
4         1.119836       -0.761543   0.806912  Rangpur

In [30]:
#Max Absolute Scalrer on whole dataset
x4.head()
from sklearn.preprocessing import MaxAbsScaler
scaler=MaxAbsScaler()
for col in x4.columns:
    if pd.api.types.is_numeric_dtype(x4[col]):
        x4[col]=scaler.fi

   Marketing Spend  Administration  Transport     Area
0        114523.61       136897.80  471784.10    Dhaka
1        162597.70       151377.59  443898.53      Ctg
2        153441.51       101145.55  407934.54  Rangpur
3        144372.41       118671.85  383199.62    Dhaka
4        142107.34        91391.77  366168.42  Rangpur