In [80]:
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
import seaborn as sns

In [81]:
df=pd.read_csv("supershops.csv")

In [82]:
df.head()

   Marketing Spend  Administration  Transport     Area     Profit
0        114523.61       136897.80  471784.10    Dhaka  192261.83
1        162597.70       151377.59  443898.53      Ctg  191792.06
2        153441.51       101145.55  407934.54  Rangpur  191050.39
3        144372.41       118671.85  383199.62    Dhaka  182901.99
4        142107.34        91391.77  366168.42  Rangpur  166187.94

In [83]:
df.isnull().sum()

Marketing Spend    0
Administration     0
Transport          1
Area               0
Profit             0
dtype: int64

In [84]:
df[df.isnull().any(axis=1)]

    Marketing Spend  Administration  Transport   Area     Profit
19          86419.7       153514.11        NaN  Dhaka  122776.86

In [85]:
df['Transport'].fillna(df['Transport'].mean(), inplace=True)

C:\Users\dipto\AppData\Local\Temp\ipykernel_1840\3123990130.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Transport'].fillna(df['Transport'].mean(), inplace=True)

In [87]:
df[df.isnull().any(axis=1)]

Empty DataFrame
Columns: [Marketing Spend, Administration, Transport, Area, Profit]
Index: []

In [88]:
print("Total Null Values:", df.isnull().sum().sum())

Total Null Values: 0

In [89]:
df1=df.copy()
df2=df.copy()
df3=df.copy()
df4=df.copy()
df5=df.copy()
df6=df.copy()
df7=df.copy()
df8=df.copy()
df9=df.copy()

In [90]:
#Label Encoding on the Area column
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()

In [91]:
df["Area"]=le.fit_transform(df["Area"])
df.head()

   Marketing Spend  Administration  Transport  Area     Profit
0        114523.61       136897.80  471784.10     1  192261.83
1        162597.70       151377.59  443898.53     0  191792.06
2        153441.51       101145.55  407934.54     2  191050.39
3        144372.41       118671.85  383199.62     1  182901.99
4        142107.34        91391.77  366168.42     2  166187.94

In [92]:
#Perform Label  Encoding using loop
for col in df1.columns:
    if df1[col].dtype == np.number:
        continue
    else:
        df1[col]=le.fit_transform(df1[col])

In [93]:
df1.head()

   Marketing Spend  Administration  Transport  Area  Profit
0               37              34         48     1      49
1               47              41         47     0      48
2               46              11         46     2      47
3               45              22         45     1      46
4               44               6         44     2      45

In [94]:
from pandas.core.dtypes.common import is_numeric_dtype

In [95]:
for c in  df2.columns:
    if is_numeric_dtype(df2[c]):
        continue
    else:
        df2[c]=le.fit_transform(df2[c])

df2.head()

   Marketing Spend  Administration  Transport  Area     Profit
0        114523.61       136897.80  471784.10     1  192261.83
1        162597.70       151377.59  443898.53     0  191792.06
2        153441.51       101145.55  407934.54     2  191050.39
3        144372.41       118671.85  383199.62     1  182901.99
4        142107.34        91391.77  366168.42     2  166187.94

In [96]:
X=df2.drop(['Profit'],axis=1)
X.shape

(50, 4)

In [97]:
Y=df2[['Profit']]
Y.shape

(50, 1)

In [98]:
from sklearn.model_selection import train_test_split

In [99]:
xtrain,xtest,ytrain,ytest=train_test_split(X,Y,random_state=42,test_size=0.30)

In [100]:
from sklearn.linear_model import LinearRegression

In [101]:
lr=LinearRegression()

In [102]:
lr.fit(xtrain,ytrain)

LinearRegression()

In [103]:
ypred = lr.predict(xtest)
print("R² score:", r2_score(ytest, ypred))
print("MSE:", mean_squared_error(ytest, ypred))
print("MAE:", mean_absolute_error(ytest, ypred))

R² score: 0.9426975379073222
MSE: 80624620.76380405
MAE: 7078.400438017701

In [104]:
#ONE HOT ENCODING
#df3.head()
dummy=pd.get_dummies(df4['Area'],dtype=int)
dummy.head()

   Ctg  Dhaka  Rangpur
0    0      1        0
1    1      0        0
2    0      0        1
3    0      1        0
4    0      0        1

In [105]:
df4=df4.drop("Area",axis=1)
#df4.drop("Area",axis=1,inplace=True)
df4.head()

   Marketing Spend  Administration  Transport     Profit
0        114523.61       136897.80  471784.10  192261.83
1        162597.70       151377.59  443898.53  191792.06
2        153441.51       101145.55  407934.54  191050.39
3        144372.41       118671.85  383199.62  182901.99
4        142107.34        91391.77  366168.42  166187.94

In [106]:
df4=pd.concat([df4,dummy],axis=1)
df4.head()

   Marketing Spend  Administration  Transport     Profit  Ctg  Dhaka  Rangpur
0        114523.61       136897.80  471784.10  192261.83    0      1        0
1        162597.70       151377.59  443898.53  191792.06    1      0        0
2        153441.51       101145.55  407934.54  191050.39    0      0        1
3        144372.41       118671.85  383199.62  182901.99    0      1        0
4        142107.34        91391.77  366168.42  166187.94    0      0        1

In [116]:
X1=df4.drop("Profit",axis=1)
X1.head()

   Marketing Spend  Administration  Transport  Ctg  Dhaka  Rangpur
0        114523.61       136897.80  471784.10    0      1        0
1        162597.70       151377.59  443898.53    1      0        0
2        153441.51       101145.55  407934.54    0      0        1
3        144372.41       118671.85  383199.62    0      1        0
4        142107.34        91391.77  366168.42    0      0        1

In [117]:
Y1=df4[['Profit']]
Y1.head()

      Profit
0  192261.83
1  191792.06
2  191050.39
3  182901.99
4  166187.94

In [118]:
xtrain1,xtest1,ytrain1,ytest1=train_test_split(X1,Y1,random_state=20,test_size=0.30)

In [119]:
lr1=LinearRegression()

In [120]:
lr1.fit(xtrain1,ytrain1)

LinearRegression()

In [122]:
ypred = lr1.predict(xtest1)
print("R² score:", r2_score(ytest1, ypred))
print("MSE:", mean_squared_error(ytest1,ypred))
print("MAE:", mean_absolute_error(ytest1,ypred))

R² score: 0.8988360017706543
MSE: 172100712.50981042
MAE: 9165.172815187938

In [123]:
df6.head()

   Marketing Spend  Administration  Transport     Area     Profit
0        114523.61       136897.80  471784.10    Dhaka  192261.83
1        162597.70       151377.59  443898.53      Ctg  191792.06
2        153441.51       101145.55  407934.54  Rangpur  191050.39
3        144372.41       118671.85  383199.62    Dhaka  182901.99
4        142107.34        91391.77  366168.42  Rangpur  166187.94

In [124]:
for col in df5.columns:
    if is_numeric_dtype(df5[col]):
        continue
    else:
        one=pd.get_dummies(df5[col],dtype=int)
        df5=df5.drop(df5[[col]],axis=1)
        df5=pd.concat([df5,one],axis=1)

In [125]:
df5.head()

   Marketing Spend  Administration  Transport     Profit  Ctg  Dhaka  Rangpur
0        114523.61       136897.80  471784.10  192261.83    0      1        0
1        162597.70       151377.59  443898.53  191792.06    1      0        0
2        153441.51       101145.55  407934.54  191050.39    0      0        1
3        144372.41       118671.85  383199.62  182901.99    0      1        0
4        142107.34        91391.77  366168.42  166187.94    0      0        1

In [126]:
#Ordinal Encoding
from sklearn.preprocessing import OrdinalEncoder

In [127]:
#city=df7["Area"].values
city=df7["Area"].unique()
city

array(['Dhaka', 'Ctg', 'Rangpur'], dtype=object)

In [128]:
ordinal=OrdinalEncoder(categories=[city])
ordinal

OrdinalEncoder(categories=[array(['Dhaka', 'Ctg', 'Rangpur'], dtype=object)])

In [129]:
encoded=ordinal.fit_transform(df7[["Area"]])
encoded

array([[0.],
       [1.],
       [2.],
       [0.],
       [2.],
       [0.],
       [1.],
       [2.],
       [0.],
       [1.],
       [2.],
       [1.],
       [2.],
       [1.],
       [2.],
       [0.],
       [1.],
       [0.],
       [2.],
       [0.],
       [1.],
       [0.],
       [2.],
       [2.],
       [0.],
       [1.],
       [2.],
       [0.],
       [2.],
       [0.],
       [2.],
       [0.],
       [1.],
       [2.],
       [1.],
       [0.],
       [2.],
       [1.],
       [0.],
       [1.],
       [1.],
       [2.],
       [1.],
       [0.],
       [1.],
       [0.],
       [2.],
       [1.],
       [0.],
       [1.]])

In [130]:
df7["Area"] = pd.DataFrame(encoded,columns=["Area"])                                                                                                                                                                       
df7.head()

   Marketing Spend  Administration  Transport  Area     Profit
0        114523.61       136897.80  471784.10   0.0  192261.83
1        162597.70       151377.59  443898.53   1.0  191792.06
2        153441.51       101145.55  407934.54   2.0  191050.39
3        144372.41       118671.85  383199.62   0.0  182901.99
4        142107.34        91391.77  366168.42   2.0  166187.94

In [134]:
df8.head()

   Marketing Spend  Administration  Transport     Area     Profit
0        114523.61       136897.80  471784.10    Dhaka  192261.83
1        162597.70       151377.59  443898.53      Ctg  191792.06
2        153441.51       101145.55  407934.54  Rangpur  191050.39
3        144372.41       118671.85  383199.62    Dhaka  182901.99
4        142107.34        91391.77  366168.42  Rangpur  166187.94

In [139]:
from sklearn.preprocessing import OrdinalEncoder

for col in df8.columns:
    if df8[col].dtype == 'object':
        ordinal = OrdinalEncoder()
        df8[col] = ordinal.fit_transform(df8[[col]])

In [140]:
df8.head()

   Marketing Spend  Administration  Transport  Area     Profit
0        114523.61       136897.80  471784.10   1.0  192261.83
1        162597.70       151377.59  443898.53   0.0  191792.06
2        153441.51       101145.55  407934.54   2.0  191050.39
3        144372.41       118671.85  383199.62   1.0  182901.99
4        142107.34        91391.77  366168.42   2.0  166187.94

In [141]:
X2=df8.drop(['Profit'],axis=1)
X2.head()

   Marketing Spend  Administration  Transport  Area
0        114523.61       136897.80  471784.10   1.0
1        162597.70       151377.59  443898.53   0.0
2        153441.51       101145.55  407934.54   2.0
3        144372.41       118671.85  383199.62   1.0
4        142107.34        91391.77  366168.42   2.0

In [146]:
Y2=df8[['Profit']]
Y2.shape

(50, 1)

In [147]:
xtrain2,xtest2,ytrain2,ytest2=train_test_split(X2,Y2,random_state=30,test_size=0.30)

In [148]:
lr2=LinearRegression()

In [149]:
lr2.fit(xtrain2,ytrain2)

LinearRegression()

In [150]:
ypred = lr2.predict(xtest2)
print("R² score:", r2_score(ytest2, ypred))
print("MSE:", mean_squared_error(ytest2,ypred))
print("MAE:", mean_absolute_error(ytest2,ypred))

R² score: 0.8768005951702849
MSE: 58807438.18900589
MAE: 5807.615399353986

LABEL ENCODING PROIDE HIGHEST PERFORMANCE OF THE MODEL